baseURL: https://athosgyalui-portfolio.netlify.app/
languageCode: en-us
title: MyWebstie2022
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      MY PORTFOLIO WEBSITE 2022
 #     AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Athos Gyalui
  blog: {}
  contact:
    address:
      - city: London, SW7 4RW
        country: United Kingdom
        street: Flat 4, 10 Grenville Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: agyalui.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 7733100445
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
    #  - icon: fa-twitter
    #    label: Twitter
    #    url: https://www.twitter.com
    #  - icon: fa-facebook
    #    label: Facebook
    #    url: https://www.facebook.com
    #  - icon: fa-instagram
    #    label: Instagram
    #    url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/athosgyalui
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/athos-g-a6991a141/
  image: ''
  name: Athos Gyalui
  navigation:
    button1:
      - name: Get in touch
        url: blogs
  #  button2:
  #    - name: Log In
  #      url: '#'
    links:
      - name: Home
        url: '#'
      - name: About me
        url: blogs
      - name: Projects
        url: blogs/ipsum
  #    - name: Elements
  #      url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpeg
        subtitle: Hobbies and aspirations
        title: About me
        url: blogs/aboutme
      - image: pic1.jpg
        subtitle: Educational and profesional journey
        title: Download resume
        url: blogs/CV_athos_website.pdf
      - image: pic_finance.jpg
        subtitle: Financial markets
        title: Risk-return of DJIA stocks
        url: blogs/risk_return
      - image: bike.jpg
        subtitle: Transportation
        title: TFL bike sharing
        url: blogs/bikes
      - image: music.jpg
        subtitle: Music
        title: Spotify musical features
        url: blogs/spotiffyhtml
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Master's in Analytics and Mangement student passionate about infrastructure, politics and sports."
    title: Summary
    url: blogs
